# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import math_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='data.proto',
  package='da.protobuf',
  serialized_pb='\n\ndata.proto\x12\x0b\x64\x61.protobuf\x1a\nmath.proto\"\xc4\x05\n\x08GameData\x12\r\n\x05\x64\x65\x62ug\x18\x01 \x01(\x08\x12\x10\n\x08map_name\x18\x02 \x01(\t\x12\x13\n\x0bserver_name\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\x12/\n\tpositions\x18\x05 \x01(\x0b\x32\x1c.da.protobuf.PlayerPositions\x12\x0e\n\x06\x63heats\x18\x06 \x01(\x08\x12+\n\x05kills\x18\x07 \x01(\x0b\x32\x1c.da.protobuf.PlayerPositions\x12,\n\x06\x64\x65\x61ths\x18\x08 \x01(\x0b\x32\x1c.da.protobuf.PlayerPositions\x12\x13\n\x0b\x63onnections\x18\t \x01(\x05\x12\x10\n\x08teamplay\x18\n \x01(\x08\x12\x1a\n\x12thirdperson_active\x18\x0b \x01(\x05\x12\x1c\n\x14thirdperson_inactive\x18\x0c \x01(\x05\x12\x16\n\x0e\x64isconnections\x18\r \x01(\x05\x12\x1f\n\x17unique_players_this_map\x18\x0e \x01(\x05\x12\x12\n\nda_version\x18\x0f \x01(\x05\x12\x19\n\x11\x63haracters_chosen\x18\x10 \x03(\t\x12\x16\n\x0eweapons_chosen\x18\x11 \x03(\x05\x12\x15\n\rskills_chosen\x18\x12 \x03(\x05\x12&\n\x05votes\x18\x13 \x03(\x0b\x32\x17.da.protobuf.VoteResult\x12\x18\n\x10weapons_chosen_s\x18\x14 \x03(\t\x12\x17\n\x0fskills_chosen_s\x18\x15 \x03(\t\x12\x10\n\x08map_time\x18\x16 \x01(\x02\x12\x11\n\tvr_active\x18\x17 \x01(\x05\x12\x13\n\x0bvr_inactive\x18\x18 \x01(\x05\x12\x18\n\x10platform_windows\x18\x19 \x01(\x05\x12\x16\n\x0eplatform_linux\x18\x1a \x01(\x05\x12\x14\n\x0cplatform_osx\x18\x1b \x01(\x05\"8\n\x0fPlayerPositions\x12%\n\x08position\x18\x01 \x03(\x0b\x32\x13.da.protobuf.Vector\"<\n\nVoteResult\x12\r\n\x05issue\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x08')




_GAMEDATA = descriptor.Descriptor(
  name='GameData',
  full_name='da.protobuf.GameData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='debug', full_name='da.protobuf.GameData.debug', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='map_name', full_name='da.protobuf.GameData.map_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='server_name', full_name='da.protobuf.GameData.server_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='da.protobuf.GameData.timestamp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='positions', full_name='da.protobuf.GameData.positions', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cheats', full_name='da.protobuf.GameData.cheats', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='kills', full_name='da.protobuf.GameData.kills', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='deaths', full_name='da.protobuf.GameData.deaths', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='connections', full_name='da.protobuf.GameData.connections', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='teamplay', full_name='da.protobuf.GameData.teamplay', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thirdperson_active', full_name='da.protobuf.GameData.thirdperson_active', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='thirdperson_inactive', full_name='da.protobuf.GameData.thirdperson_inactive', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='disconnections', full_name='da.protobuf.GameData.disconnections', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unique_players_this_map', full_name='da.protobuf.GameData.unique_players_this_map', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='da_version', full_name='da.protobuf.GameData.da_version', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='characters_chosen', full_name='da.protobuf.GameData.characters_chosen', index=15,
      number=16, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='weapons_chosen', full_name='da.protobuf.GameData.weapons_chosen', index=16,
      number=17, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='skills_chosen', full_name='da.protobuf.GameData.skills_chosen', index=17,
      number=18, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='votes', full_name='da.protobuf.GameData.votes', index=18,
      number=19, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='weapons_chosen_s', full_name='da.protobuf.GameData.weapons_chosen_s', index=19,
      number=20, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='skills_chosen_s', full_name='da.protobuf.GameData.skills_chosen_s', index=20,
      number=21, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='map_time', full_name='da.protobuf.GameData.map_time', index=21,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vr_active', full_name='da.protobuf.GameData.vr_active', index=22,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='vr_inactive', full_name='da.protobuf.GameData.vr_inactive', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='platform_windows', full_name='da.protobuf.GameData.platform_windows', index=24,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='platform_linux', full_name='da.protobuf.GameData.platform_linux', index=25,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='platform_osx', full_name='da.protobuf.GameData.platform_osx', index=26,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=748,
)


_PLAYERPOSITIONS = descriptor.Descriptor(
  name='PlayerPositions',
  full_name='da.protobuf.PlayerPositions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='position', full_name='da.protobuf.PlayerPositions.position', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=750,
  serialized_end=806,
)


_VOTERESULT = descriptor.Descriptor(
  name='VoteResult',
  full_name='da.protobuf.VoteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='issue', full_name='da.protobuf.VoteResult.issue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='details', full_name='da.protobuf.VoteResult.details', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='result', full_name='da.protobuf.VoteResult.result', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=808,
  serialized_end=868,
)

_GAMEDATA.fields_by_name['positions'].message_type = _PLAYERPOSITIONS
_GAMEDATA.fields_by_name['kills'].message_type = _PLAYERPOSITIONS
_GAMEDATA.fields_by_name['deaths'].message_type = _PLAYERPOSITIONS
_GAMEDATA.fields_by_name['votes'].message_type = _VOTERESULT
_PLAYERPOSITIONS.fields_by_name['position'].message_type = math_pb2._VECTOR
DESCRIPTOR.message_types_by_name['GameData'] = _GAMEDATA
DESCRIPTOR.message_types_by_name['PlayerPositions'] = _PLAYERPOSITIONS
DESCRIPTOR.message_types_by_name['VoteResult'] = _VOTERESULT

class GameData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMEDATA
  
  # @@protoc_insertion_point(class_scope:da.protobuf.GameData)

class PlayerPositions(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERPOSITIONS
  
  # @@protoc_insertion_point(class_scope:da.protobuf.PlayerPositions)

class VoteResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VOTERESULT
  
  # @@protoc_insertion_point(class_scope:da.protobuf.VoteResult)

# @@protoc_insertion_point(module_scope)
