# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='database.proto',
  package='da.protobuf',
  serialized_pb='\n\x0e\x64\x61tabase.proto\x12\x0b\x64\x61.protobuf\"s\n\rplayers_entry\x12\x13\n\x0b\x64\x61ily_style\x18\x01 \x01(\x02\x12\x14\n\x0cweekly_style\x18\x02 \x01(\x02\x12\x15\n\rmonthly_style\x18\x03 \x01(\x02\x12\x12\n\naccount_id\x18\x04 \x01(\x05\x12\x0c\n\x04name\x18\x05 \x01(\t\" \n\rleaders_entry\x12\x0f\n\x07leaders\x18\x01 \x03(\x05')




_PLAYERS_ENTRY = descriptor.Descriptor(
  name='players_entry',
  full_name='da.protobuf.players_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='daily_style', full_name='da.protobuf.players_entry.daily_style', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='weekly_style', full_name='da.protobuf.players_entry.weekly_style', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='monthly_style', full_name='da.protobuf.players_entry.monthly_style', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='account_id', full_name='da.protobuf.players_entry.account_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='da.protobuf.players_entry.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=146,
)


_LEADERS_ENTRY = descriptor.Descriptor(
  name='leaders_entry',
  full_name='da.protobuf.leaders_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='leaders', full_name='da.protobuf.leaders_entry.leaders', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=148,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['players_entry'] = _PLAYERS_ENTRY
DESCRIPTOR.message_types_by_name['leaders_entry'] = _LEADERS_ENTRY

class players_entry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYERS_ENTRY
  
  # @@protoc_insertion_point(class_scope:da.protobuf.players_entry)

class leaders_entry(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LEADERS_ENTRY
  
  # @@protoc_insertion_point(class_scope:da.protobuf.leaders_entry)

# @@protoc_insertion_point(module_scope)
